### ISSUE TITLE
Correlation header not present in response for 500 errors

### ISSUE THREAD

**Issue by brki** [snok/asgi-correlation-id#19]
Responses that are returned without error, or responses that are returned when an HTTPException is raised, include the correlation header name and the correlation id.

However, when an unhandled exception is raised, for example with this code:
```python
@app.get("/")
async def root():
    a = 1/0
    return {"message": "Hello!"}
```

then a 500 error is returned to the client, and the correlation header is not included.

It seems like it would be especially nice to have the correlation id included in the response headers for such cases.

**Comment by sondrelg** [comment]
From what I can tell it seems like unhandled errors ultimately get caught by the `ServerErrorMiddleware` [here](https://github.com/encode/starlette/blob/master/starlette/middleware/errors.py#L160), and that when no handlers are set, the middleware will always return a `PlainTextResponse` [here](https://github.com/encode/starlette/blob/master/starlette/middleware/errors.py#L251). Unless I'm misunderstanding something I think this means any surfaced error will always result in the headers being stripped.

It looks like we might technically be able to catch and suppress exceptions in _this_ middleware, to prevent that from happening, but that seems like overstepping for a request-id-middleware.

I think the way to fix this for Starlette and FastAPI projects might be to provide an exception handler, like the one you've posted above, in the package and document how to include it.

Would you be interested in creating a PR for this? I think the only change I would make is to export the callable without the app decorator:

```python
# asgi_correlation_id/exception_handlers/fastapi.py

from asgi_correlation_id.context import correlation_id

from fastapi import HTTPException


async def unhandled_exception_handler(request, exc):  # add type hints
    return await http_exception_handler(
        request, HTTPException(500, 'Internal server error', headers={'x-correlation-id': correlation_id.get()})
    )  # add 'Access-Control-Expose-Headers' header too - see middleware.py
```

Then a user could just import it in their `main.py` like this:

```python
# app/main.py
from asgi_correlation_id.exception_handlers.fastapi import unhandled_exception_handler
from fastapi import FastAPI

app = FastAPI(
    exception_handlers=[unhandled_exception_handler]
)

**Comment by sondrelg** [comment]
On further inspection, catching and re-raising exceptions in the middleware might accomplish the same thing. I've asked for input in the encode gitter chat - perhaps that would be the way to go.

**Comment by sondrelg** [comment]
@brki I've opened https://github.com/snok/asgi-correlation-id/pull/21. Would you mind taking a look at the changes to see if they make sense to you?

I think I've landed on a preference of just documenting exception handlers and explaining the problem, rather than providing finished exception handlers for each framework. See the PR description and let me know if you agree with this or not 🙂

**Comment by brki** [comment]
Yes, makes sense!

Thanks for adding the documentation.

**Comment by sondrelg** [comment]
Thanks for opening the issue! 👏

**Comment by JonasKs** [comment]
Hi! 

This can be fixed without adding error handlers, if the `FastAPI` app is **wrapped** in the middleware, not the middleware passed to FastAPI/Starlette.

In other words:

```python
app = FastAPI()
app.include_router(...)
app = CorrelationIdMiddleware(app=app)
```

This way, any error thrown by the inner app, will still be propagated upwards in the chain. This is how e.g. Sentry works. 

This approach is however a little annoying when e.g. writing tests. You end up doing something like this:

```python
fastapi = FastAPI()
fastapi.include_router(...)
app = CorrelationIdMiddleware(app=fastapi)
```
and then in your tests you do:
```python
from main import fastapi
fastapi.override_dependencies = ...
```
since `app` no longer is a FastAPI instance. 


So, I've decided to override [`build_middleware_stack`](https://github.com/JonasKs/fastapi-stack-utils/blob/main/fastapi_stack_utils/middleware.py#L16-L44) from `FastAPI`, and pass in middlewares (kinda the same Sentry does under the hood, just this is a bit more generic).  
Now, we can do this:

```python
patch_fastapi_middlewares(  # note - this must be done _before_  FastAPI is initialized
    middlewares=[
        Middleware(LoggingMiddleware),
        Middleware(
            CORSMiddleware,
            allow_credentials=True,
            allow_headers=['*'],
            allow_methods=['*'],
            allow_origins=['*'],
        ),
        Middleware(CorrelationIdMiddleware, header_name='Correlation-ID'),
    ]
)

app = FastAPI()  # when this is initiliazed the `build_middleware_stack` function will be called - which we've replaced
```
This way `app` is still a pure `FastAPI` class, and we don't have to have different imports for `uvicorn` / tests etc. Now CORS, correlationID, logging etc. will also still work even on 500 server errors.
