### ISSUE TITLE
Python 3.6 support through contextvars backport?

### ISSUE THREAD

**Issue by evinism** [snok/asgi-correlation-id#3]
This project looks fantastic, thanks for creating it. 

There's a relatively functional backport of contextvars to 3.6 -- I'm wondering whether or not adding it as a dependency would give this project instant python 3.6 support, or whether there's other Python 3.7 features it relies on such that that wouldn't work.

Backport [here](https://pypi.org/project/contextvars/)

**Comment by sondrelg** [comment]
Can't think of anything that would block usage other than the package dependency spec, but I'll investigate a little to double check 😊

**Comment by evinism** [comment]
ah, looking more closely, i'm wondering if https://github.com/MagicStack/contextvars/issues/2 might make it impossible, since it lacks "asyncio support", whatever exactly that entails. 

And it looks like they probably won't, sadly.

**Comment by sondrelg** [comment]
Looks like tests are passing in #4 for version 3.6 - I'm just having a little bit of trouble with the 3.10 run. Looks like I just need to tweak the dependencies a bit, but shouldn't be an issue I think.

If you want to test the branch on your project to see if it works, you should be able to install the middleware using `pip install git+https://github.com/snok/asgi-correlation-id.git@229a5f3b5c44f7e228be166587ed1efe88b75cfe`. 

If it does work for you I'd be happy to add 3.6 support since it doesn't actually impact other versions at all 🙂

**Comment by evinism** [comment]
Yep, seems to work perfectly for my use case. Thanks a ton!

**Comment by sondrelg** [comment]
Sweet! I'll push a release as soon as I can get the dependency spec to do what I want 😄 

Thanks for the suggestion 👏
